server:
  port: 8080

spring:
  application:
    name: ainotebook-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://ainotebook-auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: note-service
          uri: lb://ainotebook-note-service
          predicates:
            - Path=/api/note/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
